/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Vision2CanvasPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  aiProvider: "remote",
  apiEndpoint: "https://generativelanguage.googleapis.com/v1beta/openai",
  apiKey: "",
  modelName: "gemini-flash-latest",
  customPrompt: "",
  outputFolder: "",
  canvasScaleX: 2.5,
  canvasScaleY: 2,
  cardWidth: 320,
  cardHeight: 180,
  autoOpenCanvas: true
};

// src/settings.ts
var import_obsidian = require("obsidian");

// src/ai/promptTemplates.ts
var DEFAULT_VISION_SYSTEM_PROMPT = `
You are an expert Vision AI system specialized in converting physical handwritten notes, whiteboard diagrams, flowcharts, and mind maps into structured digital Obsidian .canvas whiteboard JSON data.

Your goal is to perform spatial OCR analysis on the input image. You must analyze both:
1. Text Content: Extract title, section text, list items, and tags accurately (Traditional Chinese / English).
2. Spatial Layout & Connections:
   - Identify discrete note cards/blocks.
   - Estimate relative 0..1000 coordinate bounding boxes for each card: { "x": 0..1000, "y": 0..1000, "width": 0..1000, "height": 0..1000 }, where (0,0) is top-left of the image.
   - Detect connecting arrows, lines, hierarchies, or grouping boxes.
   - Assign colors ('1': red/pink, '2': orange/yellow, '3': green, '4': cyan/blue, '5': purple, '6': gray) based on card role or section.

CRITICAL INSTRUCTION:
You MUST respond strictly with a valid JSON object matching the JSON Schema below. Do NOT output markdown code blocks, explanatory text, or trailing commentary.

JSON Schema:
{
  "title": "Short title describing the note canvas",
  "nodes": [
    {
      "id": "node_1",
      "title": "Optional Card Title",
      "content": "Card text content in markdown format...",
      "sectionIndex": 1,
      "relativeBox": {
        "x": 50,
        "y": 100,
        "width": 200,
        "height": 150
      },
      "category": "Category or Section Name",
      "color": "1"
    }
  ],
  "edges": [
    {
      "fromNodeId": "node_1",
      "toNodeId": "node_2",
      "label": "optional arrow text label",
      "arrowDirection": "forward"
    }
  ],
  "groups": [
    {
      "id": "group_1",
      "title": "Group Box Name",
      "nodeIds": ["node_1", "node_2"],
      "color": "5"
    }
  ]
}
`.trim();

// src/settings.ts
var Vision2CanvasSettingTab = class extends import_obsidian.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("AI Provider").setHeading();
    new import_obsidian.Setting(containerEl).setName("Connection Type").setDesc("Choose Local for LM Studio or another local OpenAI-compatible server, or Remote for a hosted API.").addDropdown((dropdown) => dropdown.addOption("remote", "Remote API").addOption("local", "Local model (LM Studio)").setValue(this.plugin.settings.aiProvider).onChange(async (value) => {
      const provider = value;
      const remoteDefault = "https://generativelanguage.googleapis.com/v1beta/openai";
      const localDefault = "http://127.0.0.1:1234/v1";
      if (provider === "local" && (!this.plugin.settings.apiEndpoint || this.plugin.settings.apiEndpoint === remoteDefault)) {
        this.plugin.settings.apiEndpoint = localDefault;
      } else if (provider === "remote" && this.plugin.settings.apiEndpoint === localDefault) {
        this.plugin.settings.apiEndpoint = remoteDefault;
      }
      this.plugin.settings.aiProvider = provider;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName("AI API Endpoint").setDesc(this.plugin.settings.aiProvider === "local" ? "Base URL of your local OpenAI-compatible server. LM Studio default: http://127.0.0.1:1234/v1" : "URL of your OpenAI-compatible API Gateway, Google AI Studio, or MLLM server.").addText((text) => text.setPlaceholder(this.plugin.settings.aiProvider === "local" ? "http://127.0.0.1:1234/v1" : "https://generativelanguage.googleapis.com/v1beta/openai").setValue(this.plugin.settings.apiEndpoint).onChange(async (value) => {
      this.plugin.settings.apiEndpoint = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc(this.plugin.settings.aiProvider === "local" ? "Optional. Leave empty for LM Studio and most local servers." : "API Key for authenticating with your AI gateway or Google AI Studio.").addText((text) => text.setPlaceholder("API Key...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Vision Model Name").setDesc("Name of the Vision MLLM model to use (e.g. gemini-flash-latest, gpt-4o, claude-3-5-sonnet).").addText((text) => text.setPlaceholder("gemini-flash-latest").setValue(this.plugin.settings.modelName).onChange(async (value) => {
      this.plugin.settings.modelName = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Canvas Output Folder").setDesc("Folder in your vault where generated .canvas files will be saved (leave empty for Vault root).").addText((text) => text.setPlaceholder("Canvases/Handwritten").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Canvas Layout & Prompt").setHeading();
    new import_obsidian.Setting(containerEl).setName("Auto-Open Canvas After Creation").setDesc("Automatically open the newly generated .canvas file in obsidian.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOpenCanvas).onChange(async (value) => {
      this.plugin.settings.autoOpenCanvas = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Custom System Prompt").setDesc("Override default System Prompt for Vision AI model.").addTextArea((text) => text.setPlaceholder(DEFAULT_VISION_SYSTEM_PROMPT).setValue(this.plugin.settings.customPrompt).onChange(async (value) => {
      this.plugin.settings.customPrompt = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/ai/visionClient.ts
var import_obsidian2 = require("obsidian");
var VisionClient = class _VisionClient {
  static DEFAULT_REMOTE_ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/openai";
  static DEFAULT_LOCAL_ENDPOINT = "http://127.0.0.1:1234/v1";
  settings;
  constructor(settings) {
    this.settings = settings;
  }
  /**
   * Analyze image via Vision MLLM API endpoint (with automatic retry for 503/429 transient errors)
   */
  async analyzeImage(base64ImageData, mimeType = "image/jpeg") {
    const configuredEndpoint = this.settings.apiEndpoint.trim();
    const baseEndpoint = this.settings.aiProvider === "local" && (!configuredEndpoint || configuredEndpoint === _VisionClient.DEFAULT_REMOTE_ENDPOINT) ? _VisionClient.DEFAULT_LOCAL_ENDPOINT : configuredEndpoint;
    const normalizedBaseEndpoint = baseEndpoint.replace(/\/+$/, "");
    const endpoint = normalizedBaseEndpoint + "/chat/completions";
    if (this.settings.aiProvider === "local") {
      await this.loadLocalModel(normalizedBaseEndpoint);
    }
    const systemPrompt = this.settings.customPrompt || DEFAULT_VISION_SYSTEM_PROMPT;
    const dataUrl = base64ImageData.startsWith("data:") ? base64ImageData : `data:${mimeType};base64,${base64ImageData}`;
    const requestBody = {
      model: this.settings.modelName || "gemini-flash-latest",
      messages: [
        {
          role: "system",
          content: systemPrompt
        },
        {
          role: "user",
          content: [
            {
              type: "text",
              text: "Please analyze this handwritten note photo and output the JSON canvas structure."
            },
            {
              type: "image_url",
              image_url: {
                url: dataUrl
              }
            }
          ]
        }
      ],
      temperature: 0.2
    };
    const headers = {
      "Content-Type": "application/json"
    };
    if (this.settings.apiKey) {
      headers["Authorization"] = `Bearer ${this.settings.apiKey}`;
    }
    const maxRetries = 3;
    let lastError = null;
    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        const response = await (0, import_obsidian2.requestUrl)({
          url: endpoint,
          method: "POST",
          headers,
          body: JSON.stringify(requestBody),
          throwOnError: false
        });
        if (response.status === 503 || response.status === 429) {
          if (attempt < maxRetries) {
            await new Promise((resolve) => window.setTimeout(resolve, 1500 * attempt));
            continue;
          }
          throw new Error(`AI API service temporarily unavailable (${response.status}). Please retry in a few seconds.`);
        }
        if (response.status >= 400) {
          throw new Error(`AI API request failed (${response.status}): ${response.text}`);
        }
        const responseJson = response.json;
        const rawContent = responseJson?.choices?.[0]?.message?.content;
        if (!rawContent) {
          throw new Error("AI API returned empty response content.");
        }
        return this.parseJsonResponse(rawContent);
      } catch (err) {
        const errorObj = err instanceof Error ? err : new Error(String(err));
        lastError = errorObj;
        if (attempt < maxRetries && (errorObj.message.includes("503") || errorObj.message.includes("429"))) {
          await new Promise((resolve) => window.setTimeout(resolve, 1500 * attempt));
          continue;
        }
        break;
      }
    }
    throw lastError || new Error("Failed to analyze image with Vision AI.");
  }
  /**
   * Loads the selected model through LM Studio's REST API before inference.
   */
  async loadLocalModel(baseEndpoint) {
    const apiRoot = baseEndpoint.endsWith("/v1") ? baseEndpoint.slice(0, -3) : baseEndpoint;
    const loadEndpoint = `${apiRoot}/api/v1/models/load`;
    const headers = {
      "Content-Type": "application/json"
    };
    if (this.settings.apiKey) {
      headers["Authorization"] = `Bearer ${this.settings.apiKey}`;
    }
    const response = await (0, import_obsidian2.requestUrl)({
      url: loadEndpoint,
      method: "POST",
      headers,
      body: JSON.stringify({
        model: this.settings.modelName,
        echo_load_config: false
      }),
      throwOnError: false
    });
    if (response.status >= 400) {
      throw new Error(
        `LM Studio could not load model "${this.settings.modelName}" (${response.status}): ${response.text}`
      );
    }
  }
  /**
   * Safe JSON parser that strips markdown ticks if present
   */
  parseJsonResponse(rawText) {
    let cleanJson = rawText.trim();
    if (cleanJson.startsWith("```json")) {
      cleanJson = cleanJson.replace(/^```json\s*/, "").replace(/\s*```$/, "");
    } else if (cleanJson.startsWith("```")) {
      cleanJson = cleanJson.replace(/^```\s*/, "").replace(/\s*```$/, "");
    }
    const parsed = JSON.parse(cleanJson);
    if (!parsed.nodes || !Array.isArray(parsed.nodes)) {
      throw new Error('Parsed JSON is missing "nodes" array.');
    }
    return parsed;
  }
};

// src/canvas/canvasBuilder.ts
var CanvasBuilder = class {
  settings;
  constructor(settings) {
    this.settings = settings;
  }
  /**
   * Main entry: Convert Vision AI analysis output into Obsidian Canvas v1 JSON structure
   */
  buildCanvasData(aiResult) {
    const nodes = [];
    const edges = [];
    const nodeIdMap = /* @__PURE__ */ new Map();
    const defaultWidth = this.settings.cardWidth || 320;
    const defaultHeight = this.settings.cardHeight || 180;
    const scaleX = this.settings.canvasScaleX || 2.5;
    const scaleY = this.settings.canvasScaleY || 2;
    aiResult.nodes.forEach((aiNode, index) => {
      const id = aiNode.id || `node_${index + 1}`;
      let x = 0;
      let y = 0;
      let width = defaultWidth;
      let height = defaultHeight;
      if (aiNode.relativeBox) {
        x = Math.round(aiNode.relativeBox.x * scaleX);
        y = Math.round(aiNode.relativeBox.y * scaleY);
        if (aiNode.relativeBox.width > 0) {
          width = Math.max(200, Math.round(aiNode.relativeBox.width * scaleX));
        }
        if (aiNode.relativeBox.height > 0) {
          height = Math.max(120, Math.round(aiNode.relativeBox.height * scaleY));
        }
      } else if (aiNode.gridPos) {
        const colMargin = 380;
        const rowMargin = 220;
        x = (aiNode.gridPos.col - 1) * colMargin;
        y = (aiNode.gridPos.row - 1) * rowMargin;
      } else if (aiNode.sectionIndex !== void 0) {
        const col = Math.max(1, aiNode.sectionIndex);
        x = (col - 1) * 380;
        const existingInCol = nodes.filter((n) => Math.abs(n.x - x) < 50);
        y = existingInCol.reduce((acc, n) => acc + n.height + 40, 0);
      } else {
        x = index % 4 * 380;
        y = Math.floor(index / 4) * 240;
      }
      let textContent = "";
      if (aiNode.title && !aiNode.content.startsWith("#")) {
        textContent = `### ${aiNode.title}

${aiNode.content}`;
      } else {
        textContent = aiNode.content;
      }
      const color = this.mapColor(aiNode.color || String(index % 6 + 1));
      const node = {
        id,
        x,
        y,
        width,
        height,
        type: "text",
        text: textContent,
        color
      };
      nodes.push(node);
      nodeIdMap.set(id, node);
    });
    if (aiResult.groups && aiResult.groups.length > 0) {
      aiResult.groups.forEach((group, gIdx) => {
        const groupNodes = group.nodeIds.map((id) => nodeIdMap.get(id)).filter((n) => n !== void 0);
        if (groupNodes.length > 0) {
          const padding = 30;
          const minX = Math.min(...groupNodes.map((n) => n.x)) - padding;
          const minY = Math.min(...groupNodes.map((n) => n.y)) - padding - 20;
          const maxX = Math.max(...groupNodes.map((n) => n.x + n.width)) + padding;
          const maxY = Math.max(...groupNodes.map((n) => n.y + n.height)) + padding;
          const groupNode = {
            id: group.id || `group_${gIdx + 1}`,
            x: minX,
            y: minY,
            width: maxX - minX,
            height: maxY - minY,
            type: "group",
            label: group.title,
            color: this.mapColor(group.color || "5")
          };
          nodes.unshift(groupNode);
        }
      });
    }
    if (aiResult.edges && aiResult.edges.length > 0) {
      aiResult.edges.forEach((aiEdge, edgeIdx) => {
        const fromNode = nodeIdMap.get(aiEdge.fromNodeId);
        const toNode = nodeIdMap.get(aiEdge.toNodeId);
        if (fromNode && toNode && aiEdge.fromNodeId !== aiEdge.toNodeId) {
          const { fromSide, toSide } = this.calculateBestConnectionSides(fromNode, toNode);
          const edge = {
            id: `edge_${edgeIdx + 1}`,
            fromNode: fromNode.id,
            fromSide,
            toNode: toNode.id,
            toSide,
            toEnd: aiEdge.arrowDirection === "none" ? "none" : "arrow",
            label: aiEdge.label || void 0
          };
          if (aiEdge.arrowDirection === "both") {
            edge.fromEnd = "arrow";
          }
          edges.push(edge);
        }
      });
    }
    return { nodes, edges };
  }
  /**
   * Smart calculation for edge attachment sides based on relative position
   */
  calculateBestConnectionSides(from, to) {
    const fromCenter = { x: from.x + from.width / 2, y: from.y + from.height / 2 };
    const toCenter = { x: to.x + to.width / 2, y: to.y + to.height / 2 };
    const dx = toCenter.x - fromCenter.x;
    const dy = toCenter.y - fromCenter.y;
    if (Math.abs(dx) > Math.abs(dy)) {
      if (dx > 0) {
        return { fromSide: "right", toSide: "left" };
      } else {
        return { fromSide: "left", toSide: "right" };
      }
    } else {
      if (dy > 0) {
        return { fromSide: "bottom", toSide: "top" };
      } else {
        return { fromSide: "top", toSide: "bottom" };
      }
    }
  }
  mapColor(colorStr) {
    if (!colorStr) return void 0;
    if (["1", "2", "3", "4", "5", "6"].includes(colorStr)) {
      return colorStr;
    }
    const lower = colorStr.toLowerCase();
    if (lower.includes("red") || lower.includes("pink")) return "1";
    if (lower.includes("orange") || lower.includes("yellow")) return "2";
    if (lower.includes("green")) return "3";
    if (lower.includes("cyan") || lower.includes("blue")) return "4";
    if (lower.includes("purple")) return "5";
    return "6";
  }
};

// src/canvas/canvasValidator.ts
var CanvasValidator = class {
  /**
   * Validates if the object adheres to Obsidian Canvas Spec v1
   */
  static validate(data) {
    const errors = [];
    if (!data || typeof data !== "object") {
      return { valid: false, errors: ["Canvas data must be a valid JSON object"] };
    }
    const obj = data;
    if (!Array.isArray(obj.nodes)) {
      errors.push('Canvas data missing "nodes" array');
    }
    if (!Array.isArray(obj.edges)) {
      errors.push('Canvas data missing "edges" array');
    }
    if (errors.length > 0) {
      return { valid: false, errors };
    }
    const nodeIds = /* @__PURE__ */ new Set();
    const nodes = obj.nodes;
    const edges = obj.edges;
    nodes.forEach((node, i) => {
      const id = node.id;
      if (!id || typeof id !== "string") {
        errors.push(`Node at index ${i} missing valid string "id"`);
      } else {
        if (nodeIds.has(id)) {
          errors.push(`Duplicate node id "${id}" at index ${i}`);
        }
        nodeIds.add(id);
      }
      if (typeof node.x !== "number" || typeof node.y !== "number") {
        errors.push(`Node "${String(id)}" has invalid numeric coordinates (x, y)`);
      }
      if (typeof node.width !== "number" || typeof node.height !== "number") {
        errors.push(`Node "${String(id)}" has invalid numeric dimensions (width, height)`);
      }
      if (typeof node.type !== "string" || !["text", "file", "link", "group"].includes(node.type)) {
        errors.push(`Node "${String(id)}" has invalid type "${String(node.type)}"`);
      }
    });
    edges.forEach((edge, i) => {
      const id = edge.id;
      const fromNode = edge.fromNode;
      const toNode = edge.toNode;
      if (!id || typeof id !== "string") {
        errors.push(`Edge at index ${i} missing valid string "id"`);
      }
      if (typeof fromNode !== "string" || !nodeIdMapHas(nodeIds, fromNode)) {
        errors.push(`Edge "${String(id)}" references non-existent fromNode "${String(fromNode)}"`);
      }
      if (typeof toNode !== "string" || !nodeIdMapHas(nodeIds, toNode)) {
        errors.push(`Edge "${String(id)}" references non-existent toNode "${String(toNode)}"`);
      }
    });
    return {
      valid: errors.length === 0,
      errors
    };
  }
};
function nodeIdMapHas(set, key) {
  return set.has(key);
}

// src/utils/fileUtils.ts
var FileUtils = class {
  /**
   * Generates a timestamped default filename for the canvas file
   */
  static generateCanvasFilename(prefix = "Note") {
    const now = /* @__PURE__ */ new Date();
    const pad = (n) => String(n).padStart(2, "0");
    const yyyy = now.getFullYear();
    const mm = pad(now.getMonth() + 1);
    const dd = pad(now.getDate());
    const hh = pad(now.getHours());
    const min = pad(now.getMinutes());
    const ss = pad(now.getSeconds());
    return `${prefix}_${yyyy}${mm}${dd}_${hh}${min}${ss}.canvas`;
  }
  /**
   * Save canvas JSON string to specified vault path
   */
  static async saveCanvasToVault(app, folderPath, filename, canvasJsonStr) {
    let cleanFolder = folderPath.trim().replace(/^\/+|\/+$/g, "");
    if (cleanFolder && !await app.vault.adapter.exists(cleanFolder)) {
      await app.vault.createFolder(cleanFolder);
    }
    const fullPath = cleanFolder ? `${cleanFolder}/${filename}` : filename;
    return await app.vault.create(fullPath, canvasJsonStr);
  }
};

// src/utils/imageUtils.ts
var ImageUtils = class {
  /**
   * Helper to convert ArrayBuffer or Buffer to Base64 string
   */
  static arrayBufferToBase64(buffer) {
    let binary = "";
    const bytes = new Uint8Array(buffer);
    const len = bytes.byteLength;
    for (let i = 0; i < len; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  /**
   * Guess MIME type from filename extension
   */
  static getMimeType(filePath) {
    const ext = filePath.split(".").pop()?.toLowerCase();
    switch (ext) {
      case "png":
        return "image/png";
      case "webp":
        return "image/webp";
      case "gif":
        return "image/gif";
      case "bmp":
        return "image/bmp";
      case "jpg":
      case "jpeg":
      default:
        return "image/jpeg";
    }
  }
  /**
   * Optimizes base64 image by resizing it if width/height > maxDimension (1600px)
   * and converting to JPEG quality 0.85 to reduce payload size for Vision AI.
   */
  static async compressImageBase64(base64Data, mimeType = "image/jpeg", maxDimension = 1600) {
    if (typeof window === "undefined") {
      return { base64: base64Data, mimeType };
    }
    const dataUrl = base64Data.startsWith("data:") ? base64Data : `data:${mimeType};base64,${base64Data}`;
    return new Promise((resolve) => {
      const img = new Image();
      img.onload = () => {
        let width = img.width;
        let height = img.height;
        if (width > maxDimension || height > maxDimension) {
          if (width > height) {
            height = Math.round(height * maxDimension / width);
            width = maxDimension;
          } else {
            width = Math.round(width * maxDimension / height);
            height = maxDimension;
          }
        }
        const canvas = document.createElement("canvas");
        if (!canvas || typeof canvas.getContext !== "function") {
          resolve({ base64: base64Data, mimeType });
          return;
        }
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext("2d");
        if (ctx) {
          ctx.drawImage(img, 0, 0, width, height);
          const compressedDataUrl = canvas.toDataURL("image/jpeg", 0.85);
          const cleanBase64 = compressedDataUrl.replace(/^data:image\/jpeg;base64,/, "");
          resolve({ base64: cleanBase64, mimeType: "image/jpeg" });
          return;
        }
        resolve({ base64: base64Data, mimeType });
      };
      img.onerror = () => {
        resolve({ base64: base64Data, mimeType });
      };
      img.src = dataUrl;
    });
  }
};

// src/ui/convertModal.ts
var import_obsidian3 = require("obsidian");
var ConvertProgressModal = class extends import_obsidian3.Modal {
  statusEl;
  detailEl;
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("vision2canvas-modal");
    contentEl.createDiv({
      text: "Vision2Canvas - Converting Note",
      cls: "vision2canvas-modal-header"
    });
    this.statusEl = contentEl.createDiv({
      cls: "vision2canvas-status"
    });
    this.updateStatus("Initializing Vision AI request...");
    this.detailEl = contentEl.createDiv({
      cls: "vision2canvas-preview-box"
    });
    this.detailEl.hide();
  }
  updateStatus(msg) {
    if (this.statusEl) {
      this.statusEl.empty();
      this.statusEl.removeClass("is-error");
      this.statusEl.createSpan({ cls: "vision2canvas-progress-spinner" });
      this.statusEl.createSpan({ text: ` ${msg}` });
    }
  }
  showSuccess(msg, details) {
    if (this.statusEl) {
      this.statusEl.empty();
      this.statusEl.removeClass("is-error");
      this.statusEl.setText(`\u2705 ${msg}`);
    }
    if (details && this.detailEl) {
      this.detailEl.show();
      this.detailEl.setText(details);
    }
  }
  showError(msg) {
    if (this.statusEl) {
      this.statusEl.empty();
      this.statusEl.addClass("is-error");
      this.statusEl.setText(`\u274C ${msg}`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var Vision2CanvasPlugin = class extends import_obsidian4.Plugin {
  settings;
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new Vision2CanvasSettingTab(this.app, this));
    this.addRibbonIcon("layout-dashboard", "Convert Clipboard Image to Canvas", () => {
      void this.convertClipboardImage();
    });
    this.addCommand({
      id: "convert-clipboard-image-to-canvas",
      name: "Convert Clipboard Image to Canvas",
      callback: () => {
        void this.convertClipboardImage();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian4.TFile && this.isImageFile(file)) {
          menu.addItem((item) => {
            item.setTitle("Convert to Obsidian Canvas Whiteboard").setIcon("layout-dashboard").onClick(() => {
              void this.convertVaultImage(file);
            });
          });
        }
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  isImageFile(file) {
    const ext = file.extension.toLowerCase();
    return ["png", "jpg", "jpeg", "webp", "gif", "bmp"].includes(ext);
  }
  /**
   * Reads an image file from the Vault and converts it to .canvas
   */
  async convertVaultImage(file) {
    const modal = new ConvertProgressModal(this.app);
    modal.open();
    try {
      modal.updateStatus(`Reading image file "${file.name}"...`);
      const arrayBuffer = await this.app.vault.readBinary(file);
      const base64Str = ImageUtils.arrayBufferToBase64(arrayBuffer);
      const mimeType = ImageUtils.getMimeType(file.path);
      await this.processImageBase64(base64Str, mimeType, file.basename, modal);
    } catch (err) {
      const errorObj = err instanceof Error ? err : new Error(String(err));
      modal.showError(errorObj.message || "Failed to process vault image");
    }
  }
  /**
   * Reads image from system clipboard and converts it to .canvas
   */
  async convertClipboardImage() {
    const modal = new ConvertProgressModal(this.app);
    modal.open();
    try {
      modal.updateStatus("Reading image from clipboard...");
      const clipboardItems = await navigator.clipboard.read();
      let imageBlob = null;
      let mimeType = "image/png";
      for (const item of clipboardItems) {
        const type = item.types.find((t) => t.startsWith("image/"));
        if (type) {
          imageBlob = await item.getType(type);
          mimeType = type;
          break;
        }
      }
      if (!imageBlob) {
        modal.showError("No image found in clipboard. Please copy an image first.");
        return;
      }
      const arrayBuffer = await imageBlob.arrayBuffer();
      const base64Str = ImageUtils.arrayBufferToBase64(arrayBuffer);
      await this.processImageBase64(base64Str, mimeType, "ClipboardNote", modal);
    } catch (err) {
      const errorObj = err instanceof Error ? err : new Error(String(err));
      modal.showError(errorObj.message || "Failed to read image from clipboard.");
    }
  }
  /**
   * Core conversion pipeline: Base64 -> Image Compression -> Vision AI -> Canvas Data -> Vault .canvas File
   */
  async processImageBase64(base64Str, mimeType, titlePrefix, modal) {
    modal.updateStatus("Optimizing image size for Vision AI...");
    const optimized = await ImageUtils.compressImageBase64(base64Str, mimeType);
    modal.updateStatus(`Sending request to Vision AI (${this.settings.modelName})...`);
    const visionClient = new VisionClient(this.settings);
    const aiResult = await visionClient.analyzeImage(optimized.base64, optimized.mimeType);
    modal.updateStatus("AI analysis complete. Building Canvas layout...");
    const canvasBuilder = new CanvasBuilder(this.settings);
    const canvasData = canvasBuilder.buildCanvasData(aiResult);
    const validation = CanvasValidator.validate(canvasData);
    if (!validation.valid) {
      throw new Error(`Generated canvas failed validation: ${validation.errors.join(", ")}`);
    }
    const canvasJsonStr = JSON.stringify(canvasData, null, 2);
    const filename = FileUtils.generateCanvasFilename(aiResult.title || titlePrefix);
    modal.updateStatus(`Saving canvas file "${filename}" to vault...`);
    const createdFile = await FileUtils.saveCanvasToVault(
      this.app,
      this.settings.outputFolder,
      filename,
      canvasJsonStr
    );
    modal.showSuccess(
      `Canvas created successfully! (${canvasData.nodes.length} nodes, ${canvasData.edges.length} edges)`,
      canvasJsonStr
    );
    new import_obsidian4.Notice(`Vision2Canvas created: ${createdFile.name}`);
    if (this.settings.autoOpenCanvas) {
      await this.app.workspace.getLeaf(true).openFile(createdFile);
    }
  }
};
